/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface MyClock {}
  interface YourClock {}
}

declare namespace LocalJSX {
  interface MyClock extends JSXBase.HTMLAttributes {}
  interface YourClock extends JSXBase.HTMLAttributes {}

  interface IntrinsicElements {
    'my-clock': MyClock;
    'your-clock': YourClock;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLMyClockElement extends Components.MyClock, HTMLStencilElement {}
  var HTMLMyClockElement: {
    prototype: HTMLMyClockElement;
    new (): HTMLMyClockElement;
  };

  interface HTMLYourClockElement extends Components.YourClock, HTMLStencilElement {}
  var HTMLYourClockElement: {
    prototype: HTMLYourClockElement;
    new (): HTMLYourClockElement;
  };

  interface HTMLElementTagNameMap {
    'my-clock': HTMLMyClockElement;
    'your-clock': HTMLYourClockElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

